//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isit420hw04JadeAndrew
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NodeOrders500Entities : DbContext
    {
        public NodeOrders500Entities()
            : base("name=NodeOrders500Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CDTable> CDTables { get; set; }
        public DbSet<Inventory> Inventories { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<SalesPersonTable> SalesPersonTables { get; set; }
        public DbSet<StoreTable> StoreTables { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
