//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isit420hw04JadeAndrew
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreTable
    {
        public StoreTable()
        {
            this.Orders = new HashSet<Order>();
            this.SalesPersonTables = new HashSet<SalesPersonTable>();
        }
    
        public int storeID { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int NumberEmployees { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<SalesPersonTable> SalesPersonTables { get; set; }
    }
}
